### ISSUE TITLE
How to make graph on AWA2 dataset?

### ISSUE THREAD

**Issue by hawklucky** [cyvius96/adgpm#2]
Did I make awa2_induced_graph by replace input and output arguments? And what the meaning of induce_parents function? Also I notice that you are construct graph with all (train + test) categories together and Would that obtain test information during training?

**Comment by yinboc** [comment]
You don't have to do that. Since for the evaluation on AwA2, we just fetch the corresponding predictions on ImageNet nodes, since AwA2 nodes is a subset of ImageNet nodes.

For the induce_parents function, it BFS from the query nodes "s" until reach the base nodes "stop_set", intuitively attach "s" to "stop_set", which is mainly due to that xml-nodes does not contain the all ImageNet-nodes for testing.

**Comment by hawklucky** [comment]
I want to know how to construct awa2 graph for training? Would you give me some help?

**Comment by yinboc** [comment]
You don't have to do that. It utilizes the exact same graph as imagenet-21k task, also the same model which is trained on imagenet-21k.

**Comment by hawklucky** [comment]
Thanks, I'll try it.

**Comment by liulu112601** [comment]
Can I ask is the results for GCNZ reported in the paper also trained on the exact same graph as imagenet-21k task, also the same model which is trained on imagenet-21k?

**Comment by yinboc** [comment]
> Can I ask is the results for GCNZ reported in the paper also trained on the exact same graph as imagenet-21k task, also the same model which is trained on imagenet-21k?

All the results of GCNZ are from the same model.
