### ISSUE TITLE
How to deal with words without valid word embedding

### ISSUE THREAD

**Issue by zhaohengz** [cyvius96/adgpm#3]
Hi, 

I noticed that some words in the test set don't have valid word embedding. How to deal with them? Are these categories ignored during evluation?

Thanks!

**Comment by yinboc** [comment]
If a node has no word-embedding, we just set the vector to be zeros with same dimension.
Details could be found in `Glove.__getitem__()` in `materials/glove.py`.

They will not be ignored during evaluation, since their predictions depends on the graph context instead of their own word-embedding only.

**Comment by zhaohengz** [comment]
That clarifys. 

Thanks!
